# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Groceries' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Groceries
  pod 'ObjectMapper'

  target 'GroceriesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GroceriesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
